cmd/catalog.go
cmd/env.go
cmd/host.go
cmd/stack.go
cmd/volume.go

So you can do cool stuff like `rancher deactivate $(rancher hosts -q)` without explicitly specifying the `ls` command.

Enable using flags for default actions

---

cmd/catalog.go

When installing a stack from a catalog template, a unauthenticated request to the catalog URL was made. This fixes this by adding basic HTTP auth headers to the request using the configured key and secret.
This fixes https://github.com/rancher/rancher/issues/7182

Added basic HTTP auth to template details request

---

README.md
package/Dockerfile

Hello!
I were setting up creation of docker image to use in our build system. Found some minor mistakes:
1. readme says binaries will be located in **build/bin**, but they are actually appear in bin folder
3. **build/bin** stays empty
4. **dist** folder also have some empty folders after build
5. added **bin/** path to Dockerfile in package 
There are still some issues I am ready to fix after discussion, before pushing this changes:
1. why we have empty **build/bin** and **dist**? Should they be removed?
2. **.dockerignore** prevents straightforward using of **package/Dockerfile** as it forbids copying of **bin/rancher**. Do you know elegant way to bypass this when using something like `docker build -f package/Dockerfile --pull -t rancher_cli .` ? Now I am simply removing .dockerignore in …

Fix binaries path build/bin -> bin

---

cmd/common.go

If a non-admin user calls the /account API, it will not return any projects. So rancher cli can not find the environment by environment name. If we use the /project API, it will return all the environments the user has. But it will only return parts of environments for an admin user if the request doesn't have the parameter all=true. So we have to add this query parameter in this case.
https://github.com/rancher/rancher/issues/9988

Use  /project API to find environment instead of /account API

---

cmd/catalog.go

Catalog packages that uses go templating, docker-compose.yml.tpl, are not deployed correctly from the rancher cli. This PR solves it.

Feat: Deploy catalog packages that uses go templating at docker compose

---

cliclient/cliclient.go
cmd/login.go

Problem:
When logging in a previous config would be used and if the cluster was
removed an error would occur
Solution:
Previous configs are no longer used for login
https://github.com/rancher/rancher/issues/11470

Stop usage of previous config on login

---

cliclient/cliclient.go
cmd/project.go
cmd/ps.go

Add flag `--cluster` for `project create` allowing specifying of cluster to create the project in outside of the currently set context.
Add `--project` flag for `ps` to specify which project `ps` will show workloads for. 
Issue https://github.com/rancher/rancher/issues/11469

Add option flags for project create and ps

---

cmd/common.go
cmd/login.go

Running `rancher login --context` will provide the output `Cluster:<cluster name> Project:<project name>`
Issue: https://github.com/rancher/rancher/issues/11465

Add flag to show current context

---

cmd/login.go

Problem:
login would not work if a path was appended to the server URL
Solution:
Drop paths from the passed in URL

Fix login to accept a path

---

cmd/cluster.go
cmd/namespace.go
cmd/node.go
cmd/project.go
cmd/ps.go

Problem:
Users are unable to specify a format on table outputs
Solution:
Add --format flag to allow customization of outputs or json blobs
Issue: https://github.com/rancher/rancher/issues/12314

Add format flag to lists

---

cmd/cluster.go

Problem:
When running `cluster create --k8s-version list` the cluster is still
being created
Solution:
After printing the versions exit
Issue: https://github.com/rancher/rancher/issues/12383

Fix version list

---

cmd/namespace.go
cmd/project.go

Problem:
When creating a project and namespace no description can be set
Solution:
Add a flag for optionally adding a description
Issue: https://github.com/rancher/rancher/issues/11461

Add description flag to project and namespace

---

cmd/cluster.go

Problem:
Some rancher servers are running SSL certs that fail validation so an
existing k8s cluster would not import through a standard kubectl call
Solution:
Output a second option using curl to download the file and pass it to
kubectl thus avoiding the SSL check
Issue: https://github.com/rancher/rancher/issues/12382

Update cluster import to print second option

---

cmd/cluster.go
cmd/namespace.go
cmd/node.go
cmd/project.go
cmd/ps.go
cmd/writer.go

Problem:
format flag only accepted json or custom
Solution:
add yaml as a new output option
Issue: https://github.com/rancher/rancher/issues/12677

Add ability to set yaml as an output option

---

cmd/project.go
cmd/ps.go

Problem:
Specifying a cluster on project create and a project using ps required
an ID
Solution:
Use the lookup by name
Update the description of the ps command
Issue: https://github.com/rancher/rancher/issues/11469

Update project create and ps to use lookup by name

---

cmd/ps.go
cmd/ssh.go

Problem:
SSH command does not accept a user or allow passing through of commands
Solution:
Add support for -l flag as well as <user>@<node> syntax
Pass through all following args to SSH
SSH can be called in three ways:
`rancher ssh <node>`
`rancher ssh -l <user> <node>`
`rancher ssh <user>@<node>`
Issue: https://github.com/rancher/rancher/issues/12897

Update ssh to accept users and pass through all args

---

main.go

Problem:
up is untested and could break things
Solution:
Hide it behind RANCHER_EXPERIMENTAL env var

Hide up command behind env var

---

cliclient/cliclient.go
vendor.conf
vendor/golang.org/x/net/context/context.go
vendor/golang.org/x/net/context/go17.go
vendor/golang.org/x/net/context/go19.go
vendor/golang.org/x/net/context/pre_go17.go
vendor/golang.org/x/net/context/pre_go19.go
vendor/golang.org/x/sync/errgroup/errgroup.go

Problem:
When creating the master client, three other clients are needed which
requires multiple calls to the rancher server. This is done synchronously
and causes large delays before the command is actually run
Solution:
Build the clients async to speed up the time it takes to build the
master client

Update cli client to build in parallel

---

cmd/context.go
cmd/login.go

Problem:
Context is not setting the new project correctly
Solution:
Save the selected project into the users config
Stop using a random name on login, this was causing the json file to grow and no way for a user to get back to using a previous config. Use a default name if none is provided.
Issue: https://github.com/rancher/rancher/issues/13235

Fix context switch

---

cmd/catalog.go
main.go

Problem:
Catalog add had the wrong command
Help output was not showing parent commands
Solution:
Fix the type
Update template to display full command
Issue: https://github.com/rancher/rancher/issues/13447

Update catalog and help output

---

cmd/app.go
cmd/common.go

Problem:
Apps of the same name deploy into the same namespace. This fails when a
namespace is owned by another project
Solution:
Apps should be deployed into a unique namespace unless specified
otherwise.
Add a flag to specify the namespace
Create a namespace with a random suffix to deploy the app into if
namespace is not specified
Issue: https://github.com/rancher/rancher/issues/13537

Fix app namespace issue

---

cmd/app.go
cmd/namespace.go

Problem:
An app creates a namespace to deploy into and depending on the system it
might not be ready when attempting to install the app
Solution:
Poll the namespace to ensure it's active before proceeding with
installing the app
Issue: https://github.com/rancher/rancher/issues/13567

Wait for namespace to be ready

---

cmd/cluster.go
main.go

Problem:
Cluster is not able to be exported
Solution:
Add sub command `rancher cluster export [name/ID]` to output a cluster yaml. 
This also unhides `up`
Issue: https://github.com/rancher/rancher/issues/14160

Export cluster

---

cmd/login.go

https://github.com/rancher/rancher/issues/15235
```
$ ./rancher_darwin-amd64 login https://self-signed.badssl.com --token a:b
FATA[0000] Unable to parse response from https://self-signed.badssl.com/v3/settings/cacerts
Error: invalid character '<' looking for beginning of value
Response:
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.10.3 (Ubuntu)</center>
</body>
</html>
```

Catch invalid JSON response from server on login

---

Dockerfile.dapper

Current CI steps return the following error
```
package github.com/golang/lint/golint: code in directory /go/src/github.com/golang/lint/golint expects import "golang.org/x/lint/golint"
The command '/bin/sh -c go get github.com/golang/lint/golint' returned a non-zero code: 1
time="2018-10-23T01:28:39Z" level=fatal msg="exit status 1"  
```
Because the golint import path moved from github to golang.org: https://github.com/golang/lint/commit/c363707d68842c977f911634e06201907b60ce58#diff-5d137a611fd4de5bdbf3200f5cf19ef6

update golint path to fix ci

---

cmd/app.go

If an answer had an equals sign within the value portion of the answer, then the answer would be silently ignored and not included in the request to the rancher server.
For example,
```console
$ rancher app install --set my.foo="a-string-with-a-=-sign" . my-app
```
Would attempt to install the chart as my-app, but the request payload would not include my.foo.
Change respects only the first equal sign within the answer and then takes all that follows as the value.

Allow equal signs to appear in the value part of an answer

---

cmd/app.go
cmd/catalog.go

Allows refreshing catalogs via the CLI.
For example:
```bash
$ rancher catalog refresh foo
$ rancher catalog refresh foo bar baz
$ rancher catalog refresh --all
```

add catalog refresh

---

cliclient/cliclient.go
vendor.conf
vendor/github.com/pkg/errors/.travis.yml
vendor/github.com/pkg/errors/README.md
vendor/github.com/pkg/errors/errors.go
vendor/github.com/pkg/errors/stack.go

Problem: CLI returns 404 when issuing "rancher project ls" command after toggle rancher project "add-local" argument from true to false. This will actually occur whenever newClient() is called by any method if project is invalid.
Solution: Added message to error produced by go routines cliclient.newMasterClient(). 
Issue: rancher/rancher#16981

Add action recommendation to 404 error.

---

cmd/common.go
cmd/common_test.go
cmd/login.go

"local" is a valid cluster id. Our parsing function wasn't allowing
for it.
https://github.com/rancher/rancher/issues/17647

Allow for local cluster when parsing context

---

cmd/common.go
cmd/multiclusterapp.go
vendor.conf
vendor/github.com/rancher/types/client/management/v3/zz_generated_catalog_template_version.go
vendor/github.com/rancher/types/client/management/v3/zz_generated_cluster.go
vendor/github.com/rancher/types/client/management/v3/zz_generated_monitoring_output.go
vendor/github.com/rancher/types/client/management/v3/zz_generated_project.go
vendor/github.com/rancher/types/client/management/v3/zz_generated_target.go
vendor/github.com/rancher/types/client/management/v3/zz_generated_template_version.go
vendor/github.com/rancher/types/client/management/v3/zz_generated_template_version_spec.go
vendor/github.com/rancher/types/client/management/v3/zz_generated_update_multi_cluster_app_targets_input.go
vendor/github.com/rancher/types/client/project/v3/zz_generated_app_upgrade_config.go

Address issue:
https://github.com/rancher/rancher/issues/17147
https://github.com/rancher/rancher/issues/17981
Related types PR: https://github.com/rancher/types/pull/726
- Add subcommand for updating target projects
- Add subcommand for updating members
- Add --member, --member-access-type option on install
- Add --role option on install/upgrade
- Add member/role details in show-app command
Examples:
```
#update targets command:
1. rancher mcapp add-project myapp mycluster:Project1 mycluster:Project2
2. rancher mcapp delete-project myapp mycluster:Project1 mycluster:Project2
3. rancher mcapp add-member myapp owner user1 user2
4. rancher mcapp delete-member myapp user1 user2
5. rancher mcapp install --member user1 --member-access-type member --target mycluster:Default mysql myapp
6. …
```

Address mcapp RBAC changes

---

cmd/common.go
cmd/globaldns.go
cmd/multiclusterapp.go
main.go
vendor.conf
vendor/github.com/rancher/types/client/management/v3/zz_generated_alidns_provider_config.go
vendor/github.com/rancher/types/client/management/v3/zz_generated_cloudflare_provider_config.go
vendor/github.com/rancher/types/client/management/v3/zz_generated_etcd_backup.go
vendor/github.com/rancher/types/client/management/v3/zz_generated_etcd_backup_spec.go
vendor/github.com/rancher/types/client/management/v3/zz_generated_global_dns_provider.go
vendor/github.com/rancher/types/client/management/v3/zz_generated_global_dns_provider_spec.go
vendor/github.com/rancher/types/client/management/v3/zz_generated_route53provider_config.go
vendor/github.com/rancher/types/client/management/v3/zz_generated_update_global_dnstargets_input.go

Address issue: https://github.com/rancher/rancher/issues/17982
- add globaldns provider/entry commands
- add create/update/delete/list-members/add-member/delete-member
commands for provider/entry
- add add-project/delete-project commands for entry
Example command flows:
```
$ rancher globaldns provider ls
$ rancher globaldns provider create dnsp --type route53 --root-domain test.dm
$ rancher globaldns provider update dnsp --root-domain sub.test.dm
$ rancher globaldns provider delete p1 p2
$ rancher globaldns provider list-members p1
$ rancher globaldns provider add-member p1 user1 user2
$ rancher globaldns provider delete-member p1 user1 user2
$ rancher globaldns entry ls
$ rancher globaldns entry create --fqdn test.dm --provider p1
$ rancher globaldns entry update ENTRY_ID --fqdn test.dm …
```

Add globaldns commands

---

cmd/multiclusterapp.go

Address issue: https://github.com/rancher/rancher/issues/18670
Problem:
Panic happens on mcapp install when talking to a 2C4G single node K8S with Rancher HA installed and a GKE cluster provisioned. It does not happen in a standalone rancher. 
Inspecting the code, it is probably because the heavy loaded Rancher/K8S takes longer time to handle the conditions thus we get nil status when fetching the mcapp object after it is created.

Fix panic on mcapp install

---

cmd/multiclusterapp.go

Address https://github.com/rancher/rancher/issues/17981#issuecomment-471649787
Problem:
When using add-member/delete-member commands, missing roles on updating mcapp
is rejected on API layer.
Solution:
Add existing roles to the input.

Add roles in add/delete-member API input

---

cmd/globaldns.go
vendor.conf
vendor/github.com/rancher/types/client/management/v3/zz_generated_backup_config.go
vendor/github.com/rancher/types/client/management/v3/zz_generated_cluster_alert_rule.go
vendor/github.com/rancher/types/client/management/v3/zz_generated_cluster_alert_rule_spec.go
vendor/github.com/rancher/types/client/management/v3/zz_generated_etcd_backup.go
vendor/github.com/rancher/types/client/management/v3/zz_generated_etcd_backup_spec.go
vendor/github.com/rancher/types/client/management/v3/zz_generated_project_alert_rule.go
vendor/github.com/rancher/types/client/management/v3/zz_generated_project_alert_rule_spec.go
vendor/github.com/rancher/types/client/management/v3/zz_generated_update_global_dnstargets_input.go

Address https://github.com/rancher/rancher/issues/17982#issuecomment-472225106
Problem:
Cannot change globalDNS target to mcapp when it aims at projects, and vice versa
Solution:
Delete existing project target when mcapp target is set,
Delete existing mcapp target when try to add project target.

Change global DNS target in a straightforward way

---

cmd/common.go
cmd/multiclusterapp.go

Address https://github.com/rancher/rancher/issues/17147#issuecomment-471712299
1. Add `list-answers` command to print current answers of a mcapp
```
$ rancher mcapp list-answers myapp
SCOPE                            QUESTION              ANSWER
Global                           mysqlDatabase         admin
Global                           mysqlPassword         abc000
Global                           mysqlUser             admin
Global                           persistence.enabled   false
Global                           service.port          3306
Global                           service.type          ClusterIP
Global                           defaultImage          true
All projects in cluster lawr-t   mysqlPassword         abc222
Project Default                  mysqlPassword         abc111 …
```

Mcapp enhancements

---

cmd/multiclusterapp.go

Address https://github.com/rancher/rancher/issues/17147#issuecomment-473434433
Do no auto rollback on upgrade failure. Keep the behavior consistent with API

Remove --rollback flag for mcapp upgrade

---

cmd/app.go
cmd/multiclusterapp.go

Problem:
Using set flag adds new answers to previous answers. This does not match the behavior of helm, which first resets existing answers.
Solution:
Delete existing answers
Issue:
https://github.com/rancher/rancher/issues/17540
Also fixes:
https://github.com/rancher/rancher/issues/17405

Reset answers when set flag is used

---

cmd/app.go
cmd/app_test.go

Address issue: https://github.com/rancher/rancher/issues/21253
Problem:
When upgrading a project scoped catalog app, the externalId is not constructed properly. Therefore, it results in a version-not-found error. The cause is that URL parsing does not preserve query orders, given that it turns to a map under the hood. It breaks since we introduced 'type' param to the externalId. 
For example, 
`catalog://?catalog=cid&type=projectCatalog&template=grafana&version=0.0.30` 
becomes 
`catalog://?catalog=cid&template=grafana&type=projectCatalog&version=0.0.30`. 
Therefore the externalId filter does not work.
Solution:
Change the url.Encode way to get externalId for a newer version

Fix project-scoped catalog app upgrade

---

cmd/app.go
cmd/common.go
cmd/multiclusterapp.go

Problem:
Rancher supports enforcing apps versions but all app templates are shown
even if they are not compatable with the version of rancher running
Solution:
Add the rancherVersion filter when getting templates so only valid app
templates are shown.
This does not stop a user from passing a version that is not considered valid for their Rancher server, the API enforces version checking for all app actions. 
Issue: https://github.com/rancher/rancher/issues/21733

Pass rancherVersion when fetching templates

---

cmd/app.go
cmd/multiclusterapp.go

Problem:
defaultVersion on an app template does not take into account the rancher
server version so attempting to use that version to install an app can
cause errors
Solution:
Use a template filtered off the rancher server version to get the latest
version of the app to default to
https://github.com/rancher/rancher/issues/22127

Use version links to determine app version to install

---

cmd/cluster.go

Problem:
Some clusters can not be exported which can cause a unfriendly error
Solution:
Validate a cluster has the export action before attempting the call
Issue: https://github.com/rancher/rancher/issues/21309

Check for cluster export action

---

cmd/multiclusterapp.go

Problem:
If the user did not
pass a name, then a blank name was printed.
Solution:
Installing print text now uses name from created app. Prior, printed
app name was taken from user passed arguments.
Issue:
https://github.com/rancher/rancher/issues/22527

Print actual mcapp name

---

cmd/catalog.go

Fix issue https://github.com/rancher/rancher/issues/22471
Tested and working

Fix: check for catalog template version is nil on rancher stack ls

---

cmd/app.go

Problem:
appRevision.Status can be nil which will cause a panic
Solution:
Validate the field is not nil before assigning internal values
https://github.com/rancher/rancher/issues/23963

Do a nil check on appRevision.Status

---

.gitignore
cmd/app.go

https://github.com/rancher/rancher/issues/20704
We use json.Unmarshal for files using JSON format, and convert the
YAML format files to JSON first and call json.Unmarshal on them as well.
The yaml to json conversion led to unquoted numbers getting converted to
scientific notation. So this commit fixes it by calling yaml.Unmarshal
directly on file with yaml format instead of converting them to json.

Call yaml.Unmarshal on values/answers file using YAML

---

cmd/app.go

**Problem**
On install, answers were only being generated if prompted for answers
**Solution**
Build answers with default responses when --no-prompt is true
**Issue**
https://github.com/rancher/rancher/issues/25514

Use default answers when setting no-prompt flag

---

cmd/catalog.go

**Problem**
Manipulating the value to an expected value when can be confusing because the value submitted is not what appears on the object
**Solution**
Use value from cli as helm version instead of changing it
**Issue**
https://github.com/rancher/rancher/issues/25262

Remove changing value passed from cli

---

cmd/app.go
cmd/multiclusterapp.go

**Problem**
On install, answers were only being generated if prompted for answers or when being passed in
**Solution**
Build answers with default question responses when --no-prompt is true
**Original PR** 
https://github.com/rancher/cli/pull/268
**How it was previously working**
when the no-prompt flag is used, it will bypass being prompted for questions
**How this PR is working** 
When the no-prompt flag is used, it will fill in the valuesYaml with the default answers to the questions without being prompted to answer the questions. By setting the defaults in the valuesYaml, it follows more closely the hierarchy of answers / values / values yaml for helm charts
**Issue**
rancher/rancher#25514

Set answers to question defaults

---

cmd/app.go

**Problem**
question.default is being set to the answers for subquestion.variable so the incorrect answers are appearing for subquestion defaults
**Solution**
use subquestion.default for the answers to the subquestion.variable
**Issue**
https://github.com/rancher/rancher/issues/25514

Incorrect value being used for subquestion default

---

cmd/app.go
cmd/app_test.go

Problem: rancher/rancher#27841
Solution: Instead of parsing the yaml as a map[string]string that would lose type information about bool variables, now parsing it as map[string]interface{}. When flattening the structure, a separate case for bool type is created so that other map members are converted to string except bool.

Fix the values processing on cli

---

cmd/kubectl_token.go

Don't want this to come up for each kubectl run, will document instead. Couldn't find a way to propagate this error up to kubectl client because the cached token is still present with CLI, it's just deleted from rancher - and it's the actual kubectl call which validates the token.

remove print msg

---

cmd/kubectl_token.go
main_test.go

It would be helpful to have an option to specify a path to the cached kubectl token to avoid changing directories requiring a fresh login.

add optional path to cache kubectl token

---

cmd/common.go
cmd/kubectl_token.go
config/config.go
config/kube_config.go
main.go

kubeconfig token will now be stored with the rest
of the rancher config rather than in the .cache
directory. The location of the config directory
can now be configured.

add global config flag and store token with config

---

cmd/kubectl_token.go

- set correct kind for ExecCredential
- update help command to reflect Rancher config dir
- check for nil timestamp

minor fixes for kubeconfig exec credential

---

cmd/project.go

Fixes https://github.com/rancher/rancher/issues/31430
Because UserPrincipalID was included when the rtb object is instantiated, if the member being added is a group then the API request has both a UserPrincipalID and a GroupPrincipalID which causes an error.
We don't need to set the UserPrincipalID when we instantiate rtb, we can just let the if/else clause set it.

Remove explicit userID

---

cmd/common.go
cmd/common_test.go
cmd/login.go

Adding new provisioning v2 format `c-m-` to regex when validating cluster-id:project-id to switch context. 
https://github.com/rancher/rancher/issues/34723
Note: I like to remove the regex as it is going to bite us back if the format changes in the future and if it serves no other important functionality. It already bit us on several issues when I search the history. https://github.com/rancher/rancher/issues/17647 https://github.com/rancher/rancher/issues/14400.
cc @dramich

Add c-m- provisioing v2 format to regex for context

---

cmd/kubectl_token.go

This will allow quotes to be used as characters in usernames and passwords because the CLI will now escape them before setting the payload for an auth request.

Escape quotes in username, password, responseType before sending auth request

---

cmd/cluster.go

Issue: https://github.com/rancher/rancher/issues/37554
Problem:
Incorrect Provider is seen for clusters using Rancher CLI:  RKE2 node driver cluster is seen as Imported and local cluster is seen as Unknown
Solutions:
fix the logic for determining the provider of a cluster.
Tests:
compile and run the cli and see the following now:
```
CURRENT   ID             STATE          NAME            PROVIDER                     NODES     CPU       RAM            PODS
*         c-4rnq9        active         jiaqi-eks2      Elastic Kubernetes Service   2         0/3.86    0/6.50 GB      0/34
c-lfr6c        active         test-c1         Rancher Kubernetes Engine    1         0/2       0/3.74 GB      0/110
c-m-27k7trsj   active         k3s-custom      K3S                          1         0/4 …
```

Fix Incorrect Providers 

---

cmd/app.go

Issue: https://github.com/rancher/rancher/issues/36332
Problem:
Charts in the old Rancher catalog are deprecated and hidden from the user. When you attempt to install any of them the Rancher cli tries to find the latest version of the chart and panics with an index out of bounds.
Solution:
This PR adds a conditional to recover from the panic gracefully, and provide an error with a description of the problem. Note this is an edge case and will most likely only be seen by users with the legacy flag enabled trying to use deprecated charts.

Fix index out of bounds when installing hidden chart

---

cmd/server.go

Issue: https://github.com/rancher/rancher/issues/37545
When running `rancher-cli servers ls`, `rancher-cli servers delete` or `rancher-cli servers switch` when there are no servers configured, the cli will still prompt the user to select a server 
Check if any servers exist within the configuration before prompting the user. If no servers are stored in the configuration, print a message to the user and do not prompt for further input. 
delete the  `cli2.json` file to clear out any server configurations 
Run `rancher-cli servers ls` and observe that it does not prompt you for input 
Run `rancher-cli servers delete` and observe that it does not prompt you for input 
Run `rancher-cli servers switch` and observe that it does not prompt you for input

Display message when no servers are available

---

cmd/cluster.go

Issue: https://github.com/rancher/rancher/issues/38515
This PR updates the error messages and usage of the `clusters add-node` command so that there is less ambiguity on its proper usage.

Update error messages and usage for add-node command

---

cmd/cluster.go
cmd/common.go

Updates cluster commands to require an explicit flag if using a cluster name instead of a cluster id. This could be a breaking change, as previously you could pass either the id or name.

Assume cluster-id as argument instead of either cluster name or id

---

cmd/cluster.go
cmd/common.go

Reverts rancher/cli#325
Issue: https://github.com/rancher/rancher/issues/37609
It appears this is not in 2.6 branch: https://github.com/rancher/cli/blob/v2.6/cmd/cluster.go#L100-L105

Revert "Assume cluster-id as argument instead of either cluster name or id"

---

Dockerfile.dapper

Add missing packages after moving Dapper image to BCI in https://github.com/rancher/cli/pull/337.

[2.7] Add missing packages after moving Dapper image to BCI

---

Dockerfile.dapper

Forward-port and cherry-pick of https://github.com/rancher/cli/pull/339.

Add missing packages after moving Dapper image to BCI

---

cmd/common.go
config/config.go
config/config_test.go
main.go

Issue: rancher/rancher#42838
The default permissions was `0644`  which is not the most secure default.
Change the default permission to `0600`. Keep same permissions for config files that already exists. Warn the user if config file is either group-readable or world-readable.
First commit moves the bulk of the loading code to `config/` module, it seems more appropriate. I also added some tests to make sure I didn't totally break anything with the move.
Second commit does the following:
- Changed the default file creation to `0600` permissions. As discussed, already existing files won't have their permissions changed, this only affects new files.
- A warning is emitted if the file is either group-readable or world-readable. The message was heavily inspired by the kubectl one. I've made it …

Create config with 0600 permissions by default

---

cmd/kubectl_token.go

Parent Issue: https://github.com/rancher/rancher/issues/41651
As per changes in https://github.com/rancher/dashboard/pull/9693 I have updated the SAML Auth login endpoint to use the new dashboard login path.

[v2.8] Update saml auth login endpoint to point toward dashboard endpoint

---

cmd/kubectl_token.go
cmd/server.go

Fix https://github.com/rancher/rancher/issues/44332
As I've moved in this PR only the fix related to the panics. I'm going to then rebase the other PR.
Some workflows will trigger panics due to assignment to nil maps, or a missing check:
```go
// sc.KubeCredentials is nil -> panics
sc.KubeCredentials[id] = cred
```
```go
serverName := cf.CurrentServer
// missing check for the existance of the value -> panics
URL := cf.Servers[serverName].URL
```
To reproduce just run a `rancher server current` without any configuration:
```
-> % rancher server current 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xa14869]
goroutine 1 [running]:
github.com/rancher/cli/cmd.serverCurrent(0xc000195b80?) …
```

Fix panics in `rancher token` and `rancher server current` commands 

---

cmd/kubectl_token.go
cmd/server.go
cmd/server_test.go
cmd/writer.go
go.mod
go.sum
main.go

Fixes https://github.com/rancher/rancher/issues/44374
This PR contains the refactor of the https://github.com/rancher/cli/pull/347.
The panics fix where added with https://github.com/rancher/cli/pull/348
Fixing the panics I took the opportunity to cleanup a bit the code (only the `server` command, to avoid a huge and "critical" refactor). The server command is pretty safe to play with.
Also some deprecated deps were updated (`terminal` and `ioutil`).
The server commands are expecting a valid server configuration:
```go
func validateServersConfig(cnf config.Config) error {
// do validation validate
}
```
This common validation was changed to a `cli.BeforeFunc` and added in the `Before` of the `server` commands.
To make test possible I moved the business logic to their dedicated func, …

Cleanup of `rancher server` command

---

Dockerfile.dapper
go.mod

Because of the bump of Rancher to Go 1.22 ([here](https://github.com/rancher/rancher/pull/44684)) we need to bump the CLI as well.
We probably needed this anyway.
Needed because of this other PR: https://github.com/rancher/cli/pull/346
Original issue: https://github.com/rancher/rancher/issues/42939

[v2.9] Bump to Go 1.22

---

cmd/common.go
cmd/kubectl_token.go
config/config.go
main.go

This is a backport PR of https://github.com/rancher/cli/pull/326 for 2.8.

[v2.8] Make runnable on windows

---

Dockerfile.dapper
go.mod

Bump of Go to 1.21 to get the latest security fixes, and fix the issue with https://github.com/rancher/cli/pull/359

[v2.8] Go1.21 update

---

.github/workflows/release.yml

The testing release `v2.9.0-rc2` failed: https://github.com/rancher/cli/actions/runs/8999212629/job/24720925994
Error was `HTTP 403: Resource not accessible by integration` because the `contents` permission was set to `read`, while the needed permission to update a release should be `write`.
Added `contents: write` permission in release workflow.

Fix GitHub Action permission to publish assets

---

.github/workflows/fossa.yml

This PR updates the action to use the Rancher org FOSSA secret instead of the repo one.

[v2.8] Use Rancher org FOSSA secret

---

.github/workflows/release.yml

This PR uploads the release assets to Google Cloud Storage.
FIx: https://github.com/rancher/rancher/issues/46068
Ref: https://github.com/rancher/dashboard/blob/master/.github/workflows/build-and-upload.yaml#L89-L110

[v2.8] Upload CLI assets to GCS

---

.github/workflows/release.yml

Ref: https://github.com/rancher/cli/pull/378
Fix for env var: https://github.com/rancher/cli/actions/runs/9892030076/job/27323739480
```
Error: google-github-actions/upload-cloud-storage failed with: ENOENT: no such file or directory, lstat '/home/runner/work/cli/cli/dist/artifacts/$VERSION'
```

[v2.8] Upload CLI assets to GCS - fix

---

.github/workflows/release.yml

This PR will fix the previous download attempts with the right path.
To validate this I create a workflow trying to upload the assets to a custom bucket: https://github.com/enrichman/cli/actions/runs/9904028207/job/27360623783
```
Uploading /home/runner/work/cli/cli/dist/artifacts/v2.8.6-rc7/rancher-darwin-amd64-v2.8.6-rc7.tar.gz to gs://ecandino-bucket/cli2/v2.8.6-rc7/rancher-darwin-amd64-v2.8.6-rc7.tar.gz
Uploading /home/runner/work/cli/cli/dist/artifacts/v2.8.6-rc7/rancher-darwin-amd64-v2.8.6-rc7.tar.xz to gs://ecandino-bucket/cli2/v2.8.6-rc7/rancher-darwin-amd64-v2.8.6-rc7.tar.xz
Uploading /home/runner/work/cli/cli/dist/artifacts/v2.8.6-rc7/rancher-darwin-arm64-v2.8.6-rc7.tar.gz to gs://ecandino-bucket/cli2/v2.8.6-rc7/rancher-darwin-arm64-v2.8.6-rc7.tar.gz
Uploading …
```

[v2.8] Upload CLI assets to GCS - fix2

---

.github/workflows/release.yml

This PR uploads the release assets to Google Cloud Storage.
FIx: https://github.com/rancher/rancher/issues/46068
Ref: https://github.com/rancher/dashboard/blob/master/.github/workflows/build-and-upload.yaml#L89-L110

[v2.9] Upload CLI assets to GCS

---

.github/workflows/fossa.yml
cmd/common.go
cmd/context.go
cmd/kubectl.go
config/config.go

Ref: https://github.com/rancher/rancher/issues/45340
Switching an empty context will cause a panic.
Added an `ErrNoServerSelected` error on the `FocusedServer()` func to force the check of a valid focused server.

Fix panic on `context switch`

---

.github/workflows/fossa.yml
cmd/common.go
cmd/context.go
cmd/kubectl.go
config/config.go

Ref: https://github.com/rancher/rancher/issues/46869
- backport: https://github.com/rancher/rancher/issues/45340
- `main` PR: https://github.com/rancher/cli/pull/386
---
Switching an empty context will cause a panic.
Added an `ErrNoServerSelected` error on the `FocusedServer()` func to force the check of a valid focused server.

[v2.9] Fix panic on `context switch`

---

.github/workflows/fossa.yml
cmd/common.go
cmd/context.go
cmd/kubectl.go
config/config.go

Ref: https://github.com/rancher/rancher/issues/46933
- backport: https://github.com/rancher/rancher/issues/45340
- `main` PR: https://github.com/rancher/cli/pull/386
---
Switching an empty context will cause a panic.
Added an `ErrNoServerSelected` error on the `FocusedServer()` func to force the check of a valid focused server.

[v2.8] Fix panic on context switch

---

config/config.go

Ref: https://github.com/rancher/cli/pull/386
This PR rollback the original error message.

Revert error message of #386

---

go.mod

The new stable BCI golang image `registry.suse.com/bci/golang:1.23` is now available.
Start building with Go 1.23 using the latest available toolchain in the BCI image.

Bump Go to 1.23.1

---

cmd/cluster.go
cmd/cluster_test.go
cmd/cmd_test.go
cmd/common.go
cmd/common_test.go
cmd/fakes_test.go
cmd/project.go
cmd/project_test.go
config/config.go
config/config_test.go
go.mod
go.sum
main_test.go

Ref: https://github.com/rancher/rancher/issues/47692

Improve cluster|project list-members subcommands

---

cmd/kubectl_token.go
cmd/kubectl_token_test.go

As described in https://github.com/rancher/rancher/issues/46997
Whenever we use `rancher token` to get a token of cluster we're currently on, instead of just verifying the token expiration date and exiting, the CLI, asks for a re-login and clears the KubeCredentials block.
This PR aims to fix that issue

Avoid overwriting entire KubeCredentials block

---

config/config.go

This PR updates `GetFilePermissionWarnings` to ignore Windows platforms. The current file permission checks are not appropriate for Windows as Go does not handle permission bits in the same way as it does on Linux. For Windows, Go will only use the owner bit, effectively turning `600` into `666`. Access Control Lists are the intended means of securing files, and the cli currently sets the ACLs properly, only allowing access to the local system and administrators.

[2.11] Avoid permissions errors on Windows

---

cliclient/cliclient.go
cmd/common.go
cmd/common_test.go
cmd/login.go
cmd/ssh.go
config/config.go

Ref: https://github.com/rancher/rancher/issues/48321
Dedicated http clients in login and ssh commands that downloads certs and an ssh key respectively currently don't respect proxy settings and don't set http timeout.
This PR fixes that and makes use of Norman's API Client Timeout and ProxyURL options and makes it possible to specify those in the server config.

Respect proxy settings and set http timeout in login and ssh commands

---

cmd/kubectl_token.go
cmd/kubectl_token_oauth.go
cmd/kubectl_token_test.go

Ref https://github.com/rancher/rancher/issues/48631
The dedicated http clients in the `token` command that are used for various needs currently don't respect proxy and timeout settings.
This PR makes sure that the http client is reused and respect proxy and timeout settings.

Respect proxy settings and timeout in token command

---

go.mod

The new BCI golang stable image registry.suse.com/bci/golang:1.23 is now available.
```sh
docker pull registry.suse.com/bci/golang:1.23
docker inspect registry.suse.com/bci/golang:1.23 | grep GOLANG_VERSION
"GOLANG_VERSION=1.23.5",
```
Update the Go toolchain to 1.23.5 to match the new BCI image.

Bump Go to 1.23.5

---

cmd/kubectl_token.go
cmd/kubectl_token_oauth.go

Ref: https://github.com/rancher/rancher/issues/48631
Fix expected HTTP status codes from rancher endpoints responsible for logging in using different auth providers (basic auth, oauth, saml).

Fix expected http status codes for different auth methods in token command

---

README.md

PR updates the docker image in the README.md usage to match the [Dockerfile](./Dockerfile) user home directory.
Following the README
```bash
% docker run --rm -it -v ./test.json:/root/.rancher/cli2.json rancher/cli2 catalog
FATA[0000] no configuration found, run `login`
```
Using the correct home dir cli image connects.
```bash
% docker run --rm -it -v ./test.json:/home/cli/.rancher/cli2.json rancher/cli2 catalog
FATA[0002] Get "https://192.168.1.216.sslip.io/v3": tls: failed to verify certificate: x509: certificate signed by unknown authority
```
This addresses https://github.com/rancher/rancher/issues/48152

Update README.md docker image usage

---

go.mod
go.sum

```
git remote -v | grep upstream
upstream	git@github.com:rancher/rancher.git (fetch)
upstream	git@github.com:rancher/rancher.git (push)
git ls-remote upstream v2.8.14
d704a664ad62446de65e482ab712ae6b07f1b6e0	refs/tags/v2.8.14
```

[v2.8] Bump rancher/rancher to v2.8.14

---

scripts/build

Using Docker (colima) on modern Apple Hardware runs container on linux/arm64. 
When did I stumble upon this? 
We use Container Images to "wrap" all necessary tools to interact with our rancher clusters. To build and install those images we use `mise`  (https://mise.jdx.dev) which resolves the correct dependency to download for us. Which is platform linux/arm64 that results in a `mise ERROR unsupported env: linux/arm64` cause there is no artefact for that platform provided.

feat: support platform linux/arm64
