rancher/cli

cmd/catalog.go, cmd/common.go, cmd/config.go, cmd/container.go, cmd/docker.go, cmd/env.go, cmd/events.go, cmd/export.go, cmd/host.go, cmd/logs.go, cmd/ps.go, cmd/restart.go, cmd/rm.go, cmd/scale.go, cmd/ssh.go, cmd/stack.go, cmd/start.go, cmd/stop.go, cmd/volume.go, cmd/wait.go, main.go
https://github.com/rancher/rancher/issues/5678
https://github.com/rancher/rancher/issues/5647
@ibuildthecloud
=> Updated help for commands

cmd/config.go
https://github.com/rancher/rancher/issues/5747
=> Fixed name to print

cmd/host.go
Exposing non-rancher host labels is useful in many cases. It helps users understand their topology at a glance.
For example, Docker Swarm:
```bash
Jamess-MacBook-Pro:cli joliver$ for f in $(env|grep DOCKER|cut -d= -f1); do unset $f; done
Jamess-MacBook-Pro:cli joliver$ rancher host
ID        HOSTNAME         STATE     IP               LABELS          DETAIL
1h76      james-10acre-1   active    10.240.0.5       swarm=master    
1h77      james-10acre-2   active    10.240.0.6       swarm=manager   
1h79      james-10acre-4   active    10.240.0.13      swarm=manager   
1h80      james-10acre-5   active    10.240.0.40                      
1h81      james-10acre-6   active    10.240.0.32                      
1h82      james-10acre-7   active    146.148.93.243
Jamess-MacBook-Pro:cli joliver$ …
```
=> Expose host labels

Dockerfile.dapper
=> Bump to Go 1.7.3

cmd/catalog.go
https://github.com/rancher/rancher/issues/7182
=> Remove name as option for catalog install

cmd/catalog.go
=> Switch Rancher version query parameter

cmd/run.go
https://github.com/rancher/rancher/issues/9132
=> add error msg for invalid -e option

cmd/up.go, cmd/wait.go, vendor.conf, vendor/github.com/rancher/rancher-compose-executor/app/app.go, vendor/github.com/rancher/rancher-compose-executor/project/commands.go, vendor/github.com/rancher/rancher-compose-executor/project/empty.go, vendor/github.com/rancher/rancher-compose-executor/project/options/types.go, vendor/github.com/rancher/rancher-compose-executor/project/options/wait.go, vendor/github.com/rancher/rancher-compose-executor/project/project.go, vendor/github.com/rancher/rancher-compose-executor/project/service.go, vendor/github.com/rancher/rancher-compose-executor/rancher/container.go, vendor/github.com/rancher/rancher-compose-executor/rancher/service.go
https://github.com/rancher/rancher/issues/8492
=> Respect wait-state flag

cmd/run.go
https://github.com/rancher/rancher/issues/9454
=> Added flags that are implemented in go-rancher

cmd/stack.go, vendor.conf, vendor/github.com/rancher/rancher-compose-executor/lookup/fileenv.go
https://github.com/rancher/rancher/issues/9305#issuecomment-325463752
=> rancher-compose-executor v0.14.18 & catalog install & up envfile multiline

vendor.conf, vendor/github.com/rancher/rancher-compose-executor/lookup/fileenv.go, vendor/github.com/rancher/rancher-compose-executor/lookup/questions.go, vendor/github.com/rancher/rancher-compose-executor/rancher/service.go
https://github.com/rancher/rancher/issues/10164
=> rancher-compose-executor v0.14.23

cmd/cluster.go, cmd/namespace.go, cmd/project.go
Problem:
Need ability to ssh into nodes
Solution:
Add node command to list and delete nodes
Add ssh command to ssh into a node that rancher controls
=> Update ByID usage

cmd/common.go, cmd/login.go
Problem:
Output does not include cluster name or details
Solution:
Update output to show cluster name, details and headers
Addresses https://github.com/rancher/rancher/issues/11466
Previous output:
```
Select your default Project:
0 cluster-f2kr2:project-4g6pr Default
1 cluster-f2kr2:project-snc8m mynewp1
2 cluster-j66nx:project-bpsg6 Default
```
New:
```
Select your default Project:
NUMBER    CLUSTER NAME    PROJECT ID                    PROJECT NAME   PROJECT DESCRIPTION
0         custom1         cluster-qhrk4:project-6sr4h   Default        Default project created for the cluster
1         cluster-rn5c7   cluster-rn5c7:project-656z2   Default        Default project created for the cluster
```
=> Update login project selection output

cmd/namespace.go, cmd/project.go
this fixes https://github.com/rancher/rancher/issues/11491
=> Update error handling to return to user

cmd/ps.go
Pods and workloads are now displayed together with their `type` stated and now follows the UI on info displayed. 
```
NAMESPACE   NAME         TYPE          STATE     IMAGE     SCALE
default     eachnode     DaemonSet     active    nginx     -
default     scalable     Deployment    active    nginx     1
default     standalone   Deployment    active    nginx     1
default     test1        Deployment    active    nginx     1
default     stateful     StatefulSet   active    nginx     1
default     dan          Pod           running   nginx     Standalone
```
=> Reformat ps to only show one set of info and update headers

cmd/common.go, cmd/login.go, vendor.conf, vendor/github.com/grantae/certinfo/LICENSE, vendor/github.com/grantae/certinfo/README.md, vendor/github.com/grantae/certinfo/certinfo.go
Update login to not require a CAcert. If none is provided attempt to pull the cert from the server and see if user accepts the server's cert. 
Update indexing of projects and don't ask for a default if there is only 1 project. 
Issue: https://github.com/rancher/rancher/issues/12252
=> Login update

cmd/cluster.go, cmd/common.go, cmd/node.go
Problem:
Cluster does not match the ui
Solution:
Update ls layout to match ui
Add new column for currently focused cluster
Add options from the UI for creation of cluster
Issue: https://github.com/rancher/rancher/issues/12313
=> Update cluster command

cmd/kubectl.go
Problem:
kubectl is using the users kubeconfig on the system and not the one
specific to the cluster
Solution:
kubectl now pulls the clusters kubeconfig and uses that to run kubectl
commands
=> Update kubectl to use cluster kubeconfig

cmd/cluster.go, cmd/common.go, cmd/project.go
Problem:
Unable to do any members actions with clusters and projects
Solution:
Add ability to add and remove members from clusters and projects
`rancher project add-member-role --role <a> --role <b> <user>`
Add new subcommands to list available roles for the cluster/project
`rancher project list-roles`
Add new subcommand to list current members/roles in a cluster/project
`rancher project list-members`
Issue: https://github.com/rancher/rancher/issues/12361
=> Member actions for cluster and project

cmd/common.go, cmd/settings.go, main.go
Problem:
Users are unable to see or set settings
Solution:
Add ability to list, get and set settings
=> Add settings command

cmd/exec.go
Problem:
Unable to run exec using the container name/ID
Solution:
Update logic to allow specifying the container name/ID
Issue: https://github.com/rancher/rancher/issues/12918
=> Fix container exec

cmd/context.go, cmd/login.go, main.go, vendor.conf, vendor/github.com/urfave/cli/.flake8, vendor/github.com/urfave/cli/.travis.yml, vendor/github.com/urfave/cli/CHANGELOG.md, vendor/github.com/urfave/cli/CODE_OF_CONDUCT.md, vendor/github.com/urfave/cli/CONTRIBUTING.md, vendor/github.com/urfave/cli/MAINTAINERS.md, vendor/github.com/urfave/cli/README.md, vendor/github.com/urfave/cli/app.go, vendor/github.com/urfave/cli/appveyor.yml, vendor/github.com/urfave/cli/category.go, vendor/github.com/urfave/cli/cli.go, vendor/github.com/urfave/cli/command.go, vendor/github.com/urfave/cli/context.go, vendor/github.com/urfave/cli/errors.go, vendor/github.com/urfave/cli/flag-types.json, vendor/github.com/urfave/cli/flag.go, vendor/github.com/urfave/cli/flag_generated.go, vendor/github.com/urfave/cli/funcs.go, vendor/github.com/urfave/cli/generate-flag-types, vendor/github.com/urfave/cli/help.go, vendor/github.com/urfave/cli/runtests, vendor/github.com/urfave/cli/sort.go
Problem:
In order to switch context login has to be ran
Solution:
Add new context commands to allow quick switching and status on the
current context
Issue https://github.com/rancher/rancher/issues/13235
=> Add context command

cmd/app.go, main.go
Problem:
Apps were unusable through the cli
Solution:
Add the apps  command with subcommands. 
Issue: https://github.com/rancher/rancher/issues/13390
=> App command

cmd/common.go, cmd/inspect.go
Problem:
Inspect requires a type to be camelcase if that's how it shows in the
schema
Solution:
Make inspect note care about case
Issue: https://github.com/rancher/rancher/issues/12831
=> Update inspect to be case insensitive

cmd/catalog.go, cmd/cluster.go, cmd/common.go, cmd/namespace.go, cmd/node.go, cmd/project.go, cmd/settings.go
Update deletes to allow passing in multiple names/IDs for the same resource.
Update ls of resources to accept --quiet to allow passing to delete
Update arg checking to stop being an error and instead show --help for the command/subcommand
=> Consistency Changes

cmd/app.go, vendor.conf, vendor/github.com/rancher/types/client/management/v3/zz_generated_azure_adconfig.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_azure_adtest_and_apply_input.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_bastion_host.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_cluster_logging.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_cluster_logging_status.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_elasticsearch_config.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_etcd_service.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_rancher_kubernetes_engine_config.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_role_template.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_splunk_config.go, vendor/github.com/rancher/types/client/project/v3/zz_generated_app.go, vendor/github.com/rancher/types/client/project/v3/zz_generated_app_spec.go, vendor/github.com/rancher/types/client/project/v3/zz_generated_app_status.go
need https://github.com/rancher/types/pull/437
=> Add ability to install charts locally

cmd/cluster.go
Problem:
rke-config has a lot of knobs which aren't currently exposed
Solution:
Add a flag to `cluster create` to pass in a JSON or YAML rke-config
Issue: https://github.com/rancher/rancher/issues/13701
=> Add flag to pass in rke-config for cluster create

cmd/login.go
https://github.com/rancher/rancher/issues/14520
=> Better error when URL cannot be parsed on login

cmd/common.go, cmd/login.go
https://github.com/rancher/rancher/issues/14448
=> Make context id configurable at login

.drone.yml
Also updated to make sure we get the right Github artifacts.
=> Fix gcs publishing

cmd/catalog.go, cmd/env.go, cmd/host.go, cmd/ps.go, cmd/secret.go, cmd/stack.go, cmd/volume.go
https://github.com/rancher/rancher/issues/15453
https://github.com/rancher/rancher/issues/9663
=> Add pagination to resourceLs functions

Dockerfile.dapper, cmd/logs.go
This fix along with the fix to [agent](https://github.com/rancher/agent/pull/284) will get `tail/lines` working but additional work in cattle-server will be needed to get the rest of the options working. 
https://github.com/rancher/rancher/issues/12924
=> Update logs command

cmd/app.go
The option will be helpful for scripting using cli.
Address issue https://github.com/rancher/rancher/issues/16177
=> add no-prompt option for app install

cmd/app.go
Address Issue https://github.com/rancher/rancher/issues/16132
=> handle forbidden error when checking new namespace

cliclient/cliclient.go, cmd/common.go, cmd/inspect.go, cmd/login.go, cmd/wait.go, main.go
Problem:
CLI asks to verify certs on login
No way to wait for a resource to be available
Solution:
Add a skip-verify flag to login
Add wait command to wait for a cluster to be in active state
Issue: https://github.com/rancher/rancher/issues/15692
=> Enhance scripting with cli by adding wait

cmd/cluster.go, cmd/common.go
https://github.com/rancher/rancher/issues/15441
https://github.com/rancher/rancher/issues/15442
=> Add quiet option to add-node and import,deprecate use of --management

cmd/app.go
Fixes cli timeout when installing app without a NOTES.txt file.
For rancher/rancher/issues/16201
=> Wait until app is installed to print notes

cliclient/cliclient.go
Problem:
ByID errors on valid resources
Solution:
Return if no error to stop fallthrough to final error
Issue: https://github.com/rancher/rancher/issues/17889 and https://github.com/rancher/rancher/issues/15692
=> Fix inspect and wait

cmd/cluster.go
Problem:
Parsing did not account for either Ki or Mi
Solution:
Update parsing to be more open
Issue: https://github.com/rancher/rancher/issues/18128
=> Update parsing of memory and cpu

cmd/multiclusterapp.go
Address issue: https://github.com/rancher/rancher/issues/18609
- Use 'project-member' as the default value
- Update description
=> update roles option for mcapp install

.drone.yml
=> update drone syntax for 1.x

cmd/cluster.go, cmd/common.go
Addresses: 
https://github.com/rancher/rancher/issues/15098
=> fix yaml keys

cmd/common.go, cmd/context.go, cmd/login.go, cmd/server.go, main.go
As per https://github.com/rancher/rancher/issues/19925, add the following commands
* rancher server current
* rancher server ls
* rancher server switch
* rancher server delete
=> #19925 add rancher server command

cmd/context.go, cmd/login.go, cmd/server.go
https://github.com/rancher/rancher/issues/20288
=> Check returned error when writing config

cmd/app.go, cmd/multiclusterapp.go
https://github.com/rancher/rancher/issues/22127
=> Use version link to find template

scripts/build
https://github.com/rancher/rancher/issues/23433
=> Update build flags

cmd/ssh.go
Some nodes (aws) use an external and internal IP address, add a flag to allow using the external IP address when attempting to ssh in. 
https://github.com/rancher/rancher/issues/13556
=> Add option to allow ssh using external IP of node

cmd/app.go
https://github.com/rancher/rancher/issues/23267
=> Add in missing word "app" to error

cmd/util_ls.go
Fixes https://github.com/rancher/rancher/issues/22177
=> Fix listing being limited to 1000

cmd/app.go
Signed-off-by: Eamon Bauman <eamon@eamonbauman.com>
https://github.com/rancher/rancher/issues/25497
=> Added force for app upgrades and rollbacks

cmd/app.go
**Problem**
When a values yaml was being passed through the cli, it would set the answers but when the template was getting edited in the ui, it would update the valuesYaml
**Solution**
Set valuesYaml when value is being used instead of answers
**Issue**
https://github.com/rancher/rancher/issues/23410
https://github.com/rancher/rancher/issues/21083
=> Values yaml

cmd/cluster.go, go.mod, go.sum, vendor/github.com/rancher/types/client/management/v3/zz_generated_cluster.go, vendor/github.com/rancher/types/client/management/v3/zz_generated_cluster_status.go, vendor/modules.txt
This doesn't change any output, just stops the n*number of clusters calls. 
Depends on https://github.com/rancher/types/pull/1133
=> Update cluster list to use nodeCount field

cmd/app.go
Reverts rancher/cli#268
These code changes did not fix root cause
=> Revert "Use default answers when setting no-prompt flag"

cmd/app.go, cmd/multiclusterapp.go
**Problem** 
Setting defaults to valueYaml results in multicluster apps not having defaults
**Solution**
Add defaults to answers only if its a multicluster app
**Issue**
https://github.com/rancher/rancher/issues/25514
=> Add defaults for mcapps

cmd/kubectl_token.go
If credential is invalid but is present in the cached directory (token's deleted from rancher), exec plugin doesn't return a proper error msg but just that `server has asked for credentials`. 
Added logic with a statement `use 'rancher token --delete tokenName' if there's an error` so users can run it to delete the cached credential, allowing them to login next time. 
Also updated keycloak provider name.
=> add logic to delete cached credential if it's invalid

cmd/kubectl_token.go, main_test.go
Removing new flag added to token command
=> Reverting to 9ac2118268dbaf99b596df4017291cd698debd06

scripts/build
Add s390x support to rancher/rancher
Part of https://github.com/rancher/rancher/issues/35501
=> Add s390x arch support

.drone.yml, scripts/create-pr-in-rancher
* Bump dapper to latest
* Remove 1.6 references
* Add script to dispatch to `rancher/rancher` on tag, so it will create a PR with the tagged version (similar to rancher/ui and rancher/dashboard)
=> [v2.6] Add dispatch to rancher/rancher to create PR

cmd/cluster.go
Fixes the `cluster create --import` command trying to import a non-existent cluster instead of creating a generic cluster for import.
First time around this project, let me know if I'm missing something!
Tracked at [rancher#37574](https://github.com/rancher/rancher/issues/37574) and https://github.com/rancher/rancher/issues/41144
=> Fix import flag for cluster create command

cmd/kubectl_token.go, cmd/server.go
Ref https://github.com/rancher/rancher/issues/44447
=> [BUG] [2.8] CLI panics when trying to kubectl after a login

.github/workflows/release.yml
Latest PR (#367) fixed the permission issue, and release went fine: https://github.com/rancher/cli/releases/tag/v2.9.0-rc3
The `sha256sum.txt` file is slightly different though, including more information.
<details>
<summary>sha256sum.txt</summary>
```
67d9c79170e5d031d691e8ac8a481570d404ddf7a5f108f98d72ce34ad3b0a89  rancher-darwin-amd64-v2.9.0-rc1.tar.gz
b9635692a9e24ca679dcfae3a37d00646ab2b55f7a53a6cb34b64efbfebcbe29  rancher-darwin-amd64-v2.9.0-rc1.tar.xz
9e40f1971a7c0e0eee1d056eb7299658662bd8ffdc2a5fd8968179e6e786cb3b  rancher-linux-amd64-v2.9.0-rc1.tar.gz
a3ecc197b32a1a5d417752dd13b4920516e159806442a76a34185fa5b35c8de1  rancher-linux-amd64-v2.9.0-rc1.tar.xz
e981adb1bf3644a09303a1d1f99dcc2009bdf6b78e1f8ec417795f029adf57c8  rancher-linux-arm-v2.9.0-rc1.tar.gz …
```
=> Removed not needed information in the `sha256sum.txt` file in release

CODEOWNERS
Add the collie team as the codeowner of rancher/cli
=> [v2.9] add codeowners file

cmd/kubectl_token.go, cmd/kubectl_token_test.go
Forwardport of https://github.com/rancher/cli/pull/374
=> [v2.9][forwardport] Small refactor (error messages)

README.md
=> Fixes Linux binary build command rancher/rancher#46780

config/config.go
Ref: https://github.com/rancher/cli/pull/388
This PR rollback the original error message.
=> [v2.8] Revert error message of #388

config/config.go
This is a cherry picked backport of https://github.com/rancher/cli/pull/398
=> [2.9] Avoid permissions errors on Windows

scripts/build
=> [v2.11] Support linux/arm64 platform

scripts/build
=> [v2.10] Support linux/arm64 platform

cmd/kubectl_token.go
Added separate printout of request id for quick and easy access in case of problems.
=> cli messaging enhancement

cmd/kubectl_token.go
Added separate printout of request id for quick and easy access in case of problems.
=> [backport 2.12] cli messaging enhancement

cmd/kubectl_token.go
Added separate printout of request id for quick and easy access in case of problems.
=> [backport 2.11] cli messaging enhancement
